django-coding-test-reactjs/django-coding-test/src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('product/', include('product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

django-coding-test-reactjs/django-coding-test/src/product/urls.py
from django.urls import path,include
from django.views.generic import TemplateView

from product.views.product import CreateProductView,ProductListView,ProductFilterView,CreateTestProduct
from product.views.variant import VariantView, VariantCreateView, VariantEditView

from .router import router

app_name = "product"

urlpatterns = [
    # Variants URLs
    path('variants/', VariantView.as_view(), name='variants'),
    path('variant/create', VariantCreateView.as_view(), name='create.variant'),
    path('variant/<int:id>/edit', VariantEditView.as_view(), name='update.variant'),

    # Products URLs
    path('create/', CreateProductView.as_view(), name='create.product'),
    path('list/', ProductListView.as_view(), name='product_list'),
    path('search/', ProductFilterView.as_view(), name='product_filter_list'),
    path(r'api/', include(router.urls)),
    
    # product create test
    path('create/test/', CreateTestProduct, name='create_product'),

]

django-coding-test-reactjs/django-coding-test/src/product/models.py
from django.db import models
from config.g_model import TimeStampMixin


# Create your models here.
class Variant(TimeStampMixin):
    title = models.CharField(max_length=40, unique=True)
    description = models.TextField()
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.title

class Product(TimeStampMixin):
    title = models.CharField(max_length=255)
    sku = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    def __str__(self):
        return self.title

class ProductImage(TimeStampMixin):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file_path = models.URLField()
    def __str__(self):
        return self.product.title

class ProductVariant(TimeStampMixin):
    variant_title = models.CharField(max_length=255)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE,related_name="product_variants")
    product = models.ForeignKey(Product, on_delete=models.CASCADE,related_name='variants')
    def __str__(self):
        return self.variant_title
    

class ProductVariantPrice(TimeStampMixin):
    product_variant_one = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, null=True,
                                            related_name='product_variant_one')
    product_variant_two = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, null=True,
                                            related_name='product_variant_two')
    product_variant_three = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, null=True,
                                              related_name='product_variant_three')
    price = models.FloatField()
    stock = models.FloatField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE,related_name='product_variant_prices')
    def __str__(self):
        return self.product.title
    

django-coding-test-reactjs/django-coding-test/src/product/forms.py
from django.forms import forms, ModelForm, CharField, TextInput, Textarea, BooleanField, CheckboxInput

from product.models import Variant


class VariantForm(ModelForm):
    class Meta:
        model = Variant
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'active': CheckboxInput(attrs={'class': 'form-check-input', 'id': 'active'})
        }

django-coding-test-reactjs/django-coding-test/src/product/views/product.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView
from django.shortcuts import render
from product.models import Product,Variant,ProductImage,ProductVariant,ProductVariantPrice
import json


class CreateProductView(generic.TemplateView):
    template_name = 'products/create.html'

    def get_context_data(self, **kwargs):
        context = super(CreateProductView, self).get_context_data(**kwargs)
        variants = Variant.objects.filter(active=True).values('id', 'title')
        context['product'] = True
        context['variants'] = list(variants.all())
        return context


class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name='products/list.html'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        variants = Variant.objects.filter(active=True)
        product_variants_list = {}
        for variant in variants:
            all_variant = list(variant.product_variants.all().values_list('variant_title').distinct())
            product_variants_list[variant.title] = all_variant

        context['product_variants'] = product_variants_list
        return context

class ProductFilterView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'products/list.html'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super(ProductFilterView, self).get_context_data(**kwargs)
        variants = Variant.objects.filter(active=True)
        product_variants_list = {}
        for variant in variants:
            all_variant = list(variant.product_variants.all().values_list('variant_title').distinct())
            product_variants_list[variant.title] = all_variant

        context['product_variants'] = product_variants_list
        return context

    def get_queryset(self):  # new
        products = Product.objects.all().distinct()
        title = self.request.GET.get("title")
        variant_title = self.request.GET.get("variant")
        date = self.request.GET.get("date")
        max_price = self.request.GET.get("price_to")
        min_price = self.request.GET.get("price_from")

        if  max_price == None or max_price=="":
            max_price = 999999
        else:
            max_price = int(self.request.GET.get("price_to"))

        if  min_price == None or min_price=="":
            min_price = 0
        else:
            min_price = int(self.request.GET.get("price_from"))
        if title:
            products = products.filter(title__icontains=title)
        if variant_title:
            products = products.filter(variants__variant_title__icontains=variant_title)
        if min_price or max_price:
            products = products.filter(product_variant_prices__price__range=(min_price, max_price))
        if date:
            products = products.filter(created_at__date=date).distinct()

        queryset = products
     
        return queryset


from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from product.models import Product, ProductImage, ProductVariant, Variant, ProductVariantPrice



'''
def CreateTestProduct(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        # save product
        product = Product.objects.create(
            title=data['product_title'],
            sku=data['sku'],
            description=data['description']
        )

        # save product images
        for image in data['images']:
            ProductImage.objects.create(
                product=product,
                path=image['path']
            )

        # save product variants
        for variant in data['variants']:
            variant_obj = Variant.objects.get(id=variant['option'])
            product_variant = ProductVariant.objects.create(
                product=product,
                variant=variant_obj,
            )

            # save tags for product variant
            for tag in variant['tags']:
                product_variant.tags.add(tag)
            product_variant.save()

        # save product variant prices
        for variant_price in data['variantPrices']:
            ProductVariantPrice.objects.create(
                product_variant=product_variant,
                title=variant_price['title'],
                price=variant_price['price'],
                stock=variant_price['stock']
            )
        return JsonResponse({"status": "success"})
    else:
        return JsonResponse({"status": "error"})
'''
@csrf_exempt
def CreateTestProduct(request):
    if request.method == "POST":
        # data = request.body
        data = json.loads(request.body)
        # Create Product
        product = Product.objects.create(
            title=data['product_title'],
            sku=data['sku'],
            description=data['description']
        )
        
        # Create Product Image
        for image in data['images']:
            ProductImage.objects.create(
                product=product,
                file_path=image
            )

        # Create Product Variants
        for variant in data['variants']:
            Product_Variant_obj = Variant.objects.get(id=variant['option'])
            for tag in variant['tags']:
                ProductVariant.objects.create(
                    variant_title=tag,
                    variant=Product_Variant_obj,
                    product=product
                )

        # Create Product Variant Prices
        for variant_price in data['variantPrices']:
            ProductVariantPrice.objects.create(
                product_variant_one=ProductVariant.objects.filter(product=product,variant_title__icontains=variant_price['title'].split('/')[0])[0],
                product_variant_two=ProductVariant.objects.filter(product=product,variant_title__icontains=variant_price['title'].split('/')[1])[0],
                product_variant_three=ProductVariant.objects.filter(product=product,variant_title__icontains=variant_price['title'].split('/')[2])[0],
                price=variant_price['price'],
                stock=variant_price['stock'],
                product=product
            )
        
        return JsonResponse({"status": "success"})
    else:
        return JsonResponse({"status": "error"})

django-coding-test-reactjs/django-coding-test/src/product/views/variant.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView

from product.forms import VariantForm
from product.models import Variant


class BaseVariantView(generic.View):
    form_class = VariantForm
    model = Variant
    template_name = 'variants/create.html'
    success_url = '/product/variants'


class VariantView(BaseVariantView, ListView):
    template_name = 'variants/list.html'
    paginate_by = 10

    def get_queryset(self):
        filter_string = {}
        print(self.request.GET)
        for key in self.request.GET:
            if self.request.GET.get(key):
                filter_string[key] = self.request.GET.get(key)
        return Variant.objects.filter(**filter_string)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = True
        context['request'] = ''
        if self.request.GET:
            context['request'] = self.request.GET['title__icontains']
        return context


class VariantCreateView(BaseVariantView, CreateView):
    pass


class VariantEditView(BaseVariantView, UpdateView):
    pk_url_kwarg = 'id'

django-coding-test-reactjs/django-coding-test/src/product/templates/products/create.html
{% extends 'backend/base.html' %}

{% block title %} Create Product {% endblock %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Create Product</h1>
        <form>{% csrf_token %}
        </form>
        <a href="{% url 'product:create.product' %}" class="float-right btn btn-primary">All Product</a>
    </div>


    <script>
    var varients = {{ variants|safe }}
    console.log(typeof varients)
    </script>

    <div id="root">
        <CreateProduct id="variants" data-variants="{{ variants|safe }}"></CreateProduct>
    </div>

{% endblock %}

django-coding-test-reactjs/django-coding-test/src/product/templates/products/list.html
{% extends 'backend/base.html' %}

{% block title %}
  Product List
{% endblock %}

{% block content %}

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Products</h1>
  </div>

  <div class="card">
    <form action="{% url 'product:product_filter_list' %}" method="get" class="card-header">
      <div class="form-row justify-content-between">
        <div class="col-md-2">
          <input type="text" name="title" placeholder="Product Title" class="form-control">
        </div>
        <div class="col-md-2">
          <select name="variant" id="" class="form-control">
            <option selected="selected" disabled="disabled">--Select A Variant--</option>
            {% for variant1, variant_name in product_variants.items %}
              <optgroup label="{{variant1}}">
                {% for title in variant_name %}
                  <option value="{{title.0}}">{{title.0}}</option>
                {% endfor %}
              </optgroup>
            {% endfor %}
          </select>
        </div>

        <div class="col-md-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">Price Range</span>
            </div>
            <input type="text" name="price_from" aria-label="First name" placeholder="From" class="form-control">
            <input type="text" name="price_to" aria-label="Last name" placeholder="To" class="form-control">
          </div>
        </div>
        <div class="col-md-2">
          <input type="date" name="date" placeholder="Date" class="form-control">
        </div>
        <div class="col-md-1">
          <button name="q" type="submit" class="btn btn-primary float-right">
            <i class="fa fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <div class="card-body">
      <div class="table-response">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Title</th>
              <th>Description</th>
              <th>Variant</th>
              <th width="150px">Action</th>
            </tr>
          </thead>

          <tbody>
            {% for product in products %}
              <tr>
                <td>{{ forloop.counter0 |add:page_obj.start_index }}</td>
                <td>{{product.title}}
                  <br>
                  Created at :
                  {{product.created_at}}</td>
                <td>{{product.description}}</td>
                <td>
                  {% for data in product.product_variant_prices.all %}
                    <dl class="row mb-0" style="height: 80px; overflow: hidden" id="variant">
                      <dt class="col-sm-3 pb-0">
                        {{data.product_variant_one.variant_title}}/
                        {{data.product_variant_two.variant_title}}/
                        {{data.product_variant_three.variant_title}}
                      </dt>
                      <dd class="col-sm-9">
                        <dl class="row mb-0">
                          <dd class="col-sm-4 pb-0">Price :
                            {{data.price}}</dd>
                          <dd class="col-sm-8 pb-0">InStock :
                            {{data.stock}}</dd>
                        </dl>
                      </dd>
                    </dl>
                  {% endfor %}
                  <button onclick="$('#variant').toggleClass('h-auto')" class="btn btn-sm btn-link">Show more
                  </button>
                </td>
                <td>
                  <div class="btn-group btn-group-sm">
                    <a href="" class="btn btn-success">Edit</a>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>

    </div>

    <div class="card-footer">
      <div class="row justify-content-between">
        {% if is_paginated %}
          <div class="col-md-6">
            <p>Showing
              {{ page_obj.start_index }}
              to
              {{ page_obj.end_index }}
              out of
              {{ paginator.count }}</p>
          </div>
          <div class="col-md-2">

            {% if is_paginated %}
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li>
                    <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                  </li>
                {% else %}
                  <li class="disabled">
                    <span>&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="active">
                      <span>{{ i }}
                        <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li>
                      <a href="?page={{ i }}">{{ i }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li>
                    <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                  </li>
                {% else %}
                  <li class="disabled">
                    <span>&raquo;</span></li>
                {% endif %}
              </ul>

            {% endif %}
          </div>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

django-coding-test-reactjs/django-coding-test/src/product/templates/products/list2.html
{% extends 'backend/base.html' %}

{% block title %} Product List {% endblock %}

{% block content %}

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Products</h1>
    </div>


    <div class="card">
        <form action="" method="get" class="card-header">
            <div class="form-row justify-content-between">
                <div class="col-md-2">
                    <input type="text" name="title" placeholder="Product Title" class="form-control">
                </div>
                <div class="col-md-2">
                    <select name="variant" id="" class="form-control">
                        <option selected disabled>--Select A Variant--</option>

                    </select>
                </div>

                <div class="col-md-3">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Price Range</span>
                        </div>
                        <input type="text" name="price_from" aria-label="First name" placeholder="From"
                               class="form-control">
                        <input type="text" name="price_to" aria-label="Last name" placeholder="To" class="form-control">
                    </div>
                </div>
                <div class="col-md-2">
                    <input type="date" name="date" placeholder="Date" class="form-control">
                </div>
                <div class="col-md-1">
                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </form>

        <div class="card-body">
            <div class="table-response">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Variant</th>
                        <th width="150px">Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        <td>1</td>
                        <td>T-Shirt <br> Created at : 25-Aug-2020</td>
                        <td>Quality product in low cost</td>
                        <td>
                            <dl class="row mb-0" style="height: 80px; overflow: hidden" id="variant">
                                <dt class="col-sm-3 pb-0">
                                    XL/ Black/ Full
                                </dt>
                                <dd class="col-sm-9">
                                    <dl class="row mb-0">
                                        <dd class="col-sm-4 pb-0">Price : 200.0</dd>
                                        <dd class="col-sm-8 pb-0">InStock : 50.</dd>
                                    </dl>
                                </dd>
                                <dt class="col-sm-3 pb-0">
                                    XL/ Black/ Half
                                </dt>
                                <dd class="col-sm-9">
                                    <dl class="row mb-0">
                                        <dd class="col-sm-4 pb-0">Price : 200.0</dd>
                                        <dd class="col-sm-8 pb-0">InStock : 50.</dd>
                                    </dl>
                                </dd>
                                <dt class="col-sm-3 pb-0">
                                    L/ Black/ Full
                                </dt>
                                <dd class="col-sm-9">
                                    <dl class="row mb-0">
                                        <dd class="col-sm-4 pb-0">Price : 200.0</dd>
                                        <dd class="col-sm-8 pb-0">InStock : 50.</dd>
                                    </dl>
                                </dd>
                                <dt class="col-sm-3 pb-0">
                                    L/ Black/ Half
                                </dt>
                                <dd class="col-sm-9">
                                    <dl class="row mb-0">
                                        <dd class="col-sm-4 pb-0">Price : 200.0</dd>
                                        <dd class="col-sm-8 pb-0">InStock : 50.</dd>
                                    </dl>
                                </dd>
                            </dl>
                            <button onclick="$('#variant').toggleClass('h-auto')" class="btn btn-sm btn-link">Show more
                            </button>
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a href="" class="btn btn-success">Edit</a>
                            </div>
                        </td>
                    </tr>
                    </tbody>

                </table>
            </div>

        </div>

        <div class="card-footer">
            <div class="row justify-content-between">
                <div class="col-md-6">
                    <p>Showing 1 to 10 out of 100</p>
                </div>
                <div class="col-md-2">

                </div>
            </div>
        </div>
    </div>
{% endblock %}